/*
 * Copyright (c) 2026 GigaDevice Semiconductor Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_GD32H75EY_M_XX_PINCTRL_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_GD32H75EY_M_XX_PINCTRL_H_

#include <dt-bindings/pinctrl/gd32-pinctrl-common.h>

/* PA pins */
#define USART0_TX_PA9     GD32_PINMUX_AF('A', 9, AF7, NO_REMAP)
#define USART0_RX_PA10    GD32_PINMUX_AF('A', 10, AF7, NO_REMAP)
#define USART1_TX_PA2     GD32_PINMUX_AF('A', 2, AF7, NO_REMAP)
#define USART1_RX_PA3     GD32_PINMUX_AF('A', 3, AF7, NO_REMAP)
#define ADC012_IN12_PC2   GD32_PINMUX_ANALOG('C', 2)
#define DAC0_OUT0_PA4     GD32_PINMUX_ANALOG('A', 4)
#define TIMER0_CH0_PA8    GD32_PINMUX_AF('A', 8, AF1, NO_REMAP)
#define TIMER0_MCH0_PA7   GD32_PINMUX_AF('A', 7, AF1, NO_REMAP)
#define SPI0_SCK_PA5      GD32_PINMUX_AF('A', 5, AF5, NO_REMAP)
#define SPI0_MOSI_PA7     GD32_PINMUX_AF('A', 7, AF5, NO_REMAP)
#define SPI0_MISO_PA6     GD32_PINMUX_AF('A', 6, AF5, NO_REMAP)
#define SPI5_SCK_PA5      GD32_PINMUX_AF('A', 5, AF8, NO_REMAP)
#define SPI5_MOSI_PA7     GD32_PINMUX_AF('A', 7, AF8, NO_REMAP)
#define SPI5_MISO_PA6     GD32_PINMUX_AF('A', 6, AF8, NO_REMAP)

/* PB pins */
#define USART2_TX_PB10    GD32_PINMUX_AF('B', 10, AF7, NO_REMAP)
#define USART2_RX_PB11    GD32_PINMUX_AF('B', 11, AF7, NO_REMAP)
#define TIMER0_MCH1_PB0   GD32_PINMUX_AF('B', 0, AF1, NO_REMAP)
#define TIMER1_CH2_PB10   GD32_PINMUX_AF('B', 10, AF1, NO_REMAP)
#define I2C0_SCL_PB6      GD32_PINMUX_AF('B', 6, AF4, NO_REMAP)
#define I2C0_SDA_PB7      GD32_PINMUX_AF('B', 7, AF4, NO_REMAP)
#define I2C1_SDA_PB11     GD32_PINMUX_AF('B', 11, AF4, NO_REMAP)
#define SPI2_SCK_PB3      GD32_PINMUX_AF('B', 3, AF6, NO_REMAP)
#define SPI2_MISO_PB4     GD32_PINMUX_AF('B', 4, AF6, NO_REMAP)
#define SPI2_MOSI_PB5     GD32_PINMUX_AF('B', 5, AF7, NO_REMAP)
#define SPI1_SCK_PB13     GD32_PINMUX_AF('B', 13, AF5, NO_REMAP)
#define CAN1_RX_PB5       GD32_PINMUX_AF('B', 5, AF9, NO_REMAP)
#define CAN1_TX_PB6       GD32_PINMUX_AF('B', 6, AF9, NO_REMAP)

/* PC pins */
#define SPI1_MISO_PC2     GD32_PINMUX_AF('C', 2, AF5, NO_REMAP)
#define SPI1_MOSI_PC3     GD32_PINMUX_AF('C', 3, AF5, NO_REMAP)

/* PD pins */
#define CAN0_RX_PD0       GD32_PINMUX_AF('D', 0, AF9, NO_REMAP)
#define CAN0_TX_PD1       GD32_PINMUX_AF('D', 1, AF9, NO_REMAP)
#define SPI3_IO2_PD14     GD32_PINMUX_AF('D', 14, AF5, NO_REMAP)
#define SPI3_IO3_PD15     GD32_PINMUX_AF('D', 15, AF5, NO_REMAP)

/* PE pins */
#define TIMER0_CH1_PE11   GD32_PINMUX_AF('E', 11, AF1, NO_REMAP)
#define TIMER0_CH2_PE13   GD32_PINMUX_AF('E', 13, AF1, NO_REMAP)
#define TIMER0_MCH2_PE12  GD32_PINMUX_AF('E', 12, AF1, NO_REMAP)
#define SPI3_SCK_PE2      GD32_PINMUX_AF('E', 2, AF5, NO_REMAP)
#define SPI3_MOSI_PE6     GD32_PINMUX_AF('E', 6, AF5, NO_REMAP)
#define SPI3_MISO_PE5     GD32_PINMUX_AF('E', 5, AF5, NO_REMAP)

/* PF pins */
#define SPI4_MOSI_PF9     GD32_PINMUX_AF('F', 9, AF5, NO_REMAP)
#define CAN2_RX_PF6       GD32_PINMUX_AF('F', 6, AF9, NO_REMAP)
#define CAN2_TX_PF7       GD32_PINMUX_AF('F', 7, AF9, NO_REMAP)

/* PH pins */
#define I2C1_SCL_PH4      GD32_PINMUX_AF('H', 4, AF4, NO_REMAP)
#define I2C3_SCL_PH1      GD32_PINMUX_AF('H', 1, AF4, NO_REMAP)
#define I2C3_SDA_PH2      GD32_PINMUX_AF('H', 2, AF4, NO_REMAP)
#define SPI4_SCK_PH6      GD32_PINMUX_AF('H', 6, AF5, NO_REMAP)
#define SPI4_MISO_PH7     GD32_PINMUX_AF('H', 7, AF5, NO_REMAP)
#define SPI4_IO2_PH8      GD32_PINMUX_AF('H', 8, AF5, NO_REMAP)
#define SPI4_IO3_PH9      GD32_PINMUX_AF('H', 9, AF5, NO_REMAP)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_GD32H75EY_M_XX_PINCTRL_H_ */
