/*
 * Copyright (c) 2026 GigaDevice Semiconductor Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SOC_ARM_GIGADEVICE_GD32H7XX_GD32_REGS_H_
#define SOC_ARM_GIGADEVICE_GD32H7XX_GD32_REGS_H_

#include <zephyr/sys/util_macro.h>

/* RCU */
#define RCU_CFG0_OFFSET      0x08U
#define RCU_AHB1EN_OFFSET    0x30U
#define RCU_AHB2EN_OFFSET    0x34U
#define RCU_AHB3EN_OFFSET    0x38U
#define RCU_AHB4EN_OFFSET    0x3CU
#define RCU_APB1EN_OFFSET    0x40U
#define RCU_APB2EN_OFFSET    0x44U
#define RCU_APB3EN_OFFSET    0x48U
#define RCU_APB4EN_OFFSET    0x4CU
#define RCU_BDCTL_OFFSET     0x70U
#define RCU_CFG1_OFFSET      0x8CU
#define RCU_CFG2_OFFSET      0x90U
#define RCU_CFG3_OFFSET      0x94U
#define RCU_CFG4_OFFSET      0xD0U
#define RCU_ADDAPB2EN_OFFSET 0xE4U
#define RCU_CFG5_OFFSET      0xF0U

#define RCU_CFG0_AHBPSC_POS  4U
#define RCU_CFG0_AHBPSC_MSK  (BIT_MASK(4) << RCU_CFG0_AHBPSC_POS)
#define RCU_CFG0_APB1PSC_POS 10U
#define RCU_CFG0_APB1PSC_MSK (BIT_MASK(3) << RCU_CFG0_APB1PSC_POS)
#define RCU_CFG0_APB2PSC_POS 13U
#define RCU_CFG0_APB2PSC_MSK (BIT_MASK(3) << RCU_CFG0_APB2PSC_POS)
#define RCU_CFG0_APB4PSC_POS 24U
#define RCU_CFG0_APB4PSC_MSK (BIT_MASK(3) << RCU_CFG0_APB4PSC_POS)
#define RCU_CFG0_APB3PSC_POS 27U
#define RCU_CFG0_APB3PSC_MSK (BIT_MASK(3) << RCU_CFG0_APB3PSC_POS)
#define RCU_CFG0_I2C0SEL_POS 30U
#define RCU_CFG0_I2C0SEL_MSK (BIT_MASK(2) << RCU_CFG0_I2C0SEL_POS)

/* RCU_CFG1 */
#define RCU_CFG1_USART0SEL_POS 0U
#define RCU_CFG1_USART0SEL_MSK (BIT_MASK(2) << RCU_CFG1_USART0SEL_POS)
#define RCU_CFG1_RSPDIFSEL_POS 4U
#define RCU_CFG1_RSPDIFSEL_MSK (BIT_MASK(2) << RCU_CFG1_RSPDIFSEL_POS)
#define RCU_CFG1_CAN0SEL_POS   8
#define RCU_CFG1_CAN0SEL_MSK   (BIT_MASK(2) << RCU_CFG1_CAN0SEL_POS)
#define RCU_CFG1_CAN1SEL_POS   10
#define RCU_CFG1_CAN1SEL_MSK   (BIT_MASK(2) << RCU_CFG1_CAN1SEL_POS)
#define RCU_CFG1_CAN2SEL_POS   12
#define RCU_CFG1_CAN2SEL_MSK   (BIT_MASK(2) << RCU_CFG1_CAN2SEL_POS)
#define RCU_CFG1_PERSEL_POS    14
#define RCU_CFG1_PERSEL_MSK    (BIT_MASK(2) << RCU_CFG1_PERSEL_POS)
#define RCU_CFG1_USART1SEL_POS 18U
#define RCU_CFG1_USART1SEL_MSK (BIT_MASK(2) << RCU_CFG1_USART1SEL_POS)
#define RCU_CFG1_USART2SEL_POS 20U
#define RCU_CFG1_USART2SEL_MSK (BIT_MASK(2) << RCU_CFG1_USART2SEL_POS)
#define RCU_CFG1_USART5SEL_POS 22U
#define RCU_CFG1_USART5SEL_MSK (BIT_MASK(2) << RCU_CFG1_USART5SEL_POS)
#define RCU_CFG1_TIMERSEL_POS  24U
#define RCU_CFG1_TIMERSEL_MSK  (BIT_MASK(1) << RCU_CFG1_TIMERSEL_POS)
#define RCU_CFG1_HPDFSEL_POS   31U
#define RCU_CFG1_HPDFSEL_MSK   (BIT_MASK(1) << RCU_CFG1_HPDFSEL_POS)

/* RCU_CFG2 */
#define RCU_CFG2_SAI0SEL_POS   16U
#define RCU_CFG2_SAI0SEL_MSK   (BIT_MASK(3) << RCU_CFG2_SAI0SEL_POS)
#define RCU_CFG2_SAI1SEL_POS   20U
#define RCU_CFG2_SAI1SEL_MSK   (BIT_MASK(3) << RCU_CFG2_SAI1SEL_POS)
#define RCU_CFG2_SAI2B0SEL_POS 24U
#define RCU_CFG2_SAI2B0SEL_MSK (BIT_MASK(3) << RCU_CFG2_SAI2B0SEL_POS)
#define RCU_CFG2_SAI2B1SEL_POS 28U
#define RCU_CFG2_SAI2B1SEL_MSK (BIT_MASK(3) << RCU_CFG2_SAI2B1SEL_POS)

/* RCU_CFG3 */
#define RCU_CFG3_I2C1SEL_POS  0U
#define RCU_CFG3_I2C1SEL_MSK  (BIT_MASK(2) << RCU_CFG3_I2C1SEL_POS)
#define RCU_CFG3_I2C2SEL_POS  2U
#define RCU_CFG3_I2C2SEL_MSK  (BIT_MASK(2) << RCU_CFG3_I2C2SEL_POS)
#define RCU_CFG3_I2C3SEL_POS  4U
#define RCU_CFG3_I2C3SEL_MSK  (BIT_MASK(2) << RCU_CFG3_I2C3SEL_POS)
#define RCU_CFG3_SDIO1SEL_POS 12U
#define RCU_CFG3_SDIO1SEL_MSK (BIT_MASK(1) << RCU_CFG3_SDIO1SEL_POS)
#define RCU_CFG3_DSPWUSEL_POS 24U
#define RCU_CFG3_DSPWUSEL_MSK (BIT_MASK(1) << RCU_CFG3_DSPWUSEL_POS)
#define RCU_CFG3_ADCO1SEL_POS 26U
#define RCU_CFG3_ADC01SEL_MSK (BIT_MASK(2) << RCU_CFG3_ADCO1SEL_POS)
#define RCU_CFG3_ADC2SEL_POS  28U
#define RCU_CFG3_ADC2SEL_MSK  (BIT_MASK(2) << RCU_CFG3_ADC2SEL_POS)

/* RCU_CFG4 */
#define RCU_CFG4_SDIO0SEL_POS 0U
#define RCU_CFG4_SDIO0SEL_MSK (BIT_MASK(1) << RCU_CFG4_SDIO0SEL_POS)
#define RCU_CFG4_EXMCSEL_POS  8U
#define RCU_CFG4_EXMCSEL_MSK  (BIT_MASK(2) << RCU_CFG4_EXMCSEL_POS)

/* RCU_CFG5 */
#define RCU_CFG5_SPI0SEL_POS 0U
#define RCU_CFG5_SPI0SEL_MSK (BIT_MASK(3) << RCU_CFG5_SPI0SEL_POS)
#define RCU_CFG5_SPI1SEL_POS 4U
#define RCU_CFG5_SPI1SEL_MSK (BIT_MASK(3) << RCU_CFG5_SPI1SEL_POS)
#define RCU_CFG5_SPI2SEL_POS 8U
#define RCU_CFG5_SPI2SEL_MSK (BIT_MASK(3) << RCU_CFG5_SPI2SEL_POS)
#define RCU_CFG5_SPI3SEL_POS 12U
#define RCU_CFG5_SPI3SEL_MSK (BIT_MASK(3) << RCU_CFG5_SPI3SEL_POS)
#define RCU_CFG5_SPI4SEL_POS 16U
#define RCU_CFG5_SPI4SEL_MSK (BIT_MASK(3) << RCU_CFG5_SPI4SEL_POS)
#define RCU_CFG5_SPI5SEL_POS 20U
#define RCU_CFG5_SPI5SEL_MSK (BIT_MASK(3) << RCU_CFG5_SPI5SEL_POS)

#endif /* SOC_ARM_GIGADEVICE_GD32H7XX_GD32_REGS_H_ */
