/*
 * Copyright (c) 2026 GigaDevice Semiconductor Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RESET_GD32M531_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_RESET_GD32M531_H_

/**
 * @file
 * @brief GD32M53x (M531) peripheral reset bindings.
 */

#include "gd32-common.h"

/** @cond INTERNAL_HIDDEN */

/**
 * @name Register offsets
 * @{
 */

#define GD32_AHBRST_OFFSET      0x28U
#define GD32_APB2RST_OFFSET     0x0CU
#define GD32_APB1RST_OFFSET     0x10U

/** @} */

/**
 * @name Reset definitions for peripherals
 * @{
 */

/* AHB peripherals */
#define GD32_RESET_DMA0         GD32_RESET_CONFIG(AHBRST, 0U)
#define GD32_RESET_DMA1         GD32_RESET_CONFIG(AHBRST, 1U)
#define GD32_RESET_CRC          GD32_RESET_CONFIG(AHBRST, 6U)
#define GD32_RESET_GPIOA        GD32_RESET_CONFIG(AHBRST, 17U)
#define GD32_RESET_GPIOB        GD32_RESET_CONFIG(AHBRST, 18U)
#define GD32_RESET_GPIOC        GD32_RESET_CONFIG(AHBRST, 19U)
#define GD32_RESET_GPIOD        GD32_RESET_CONFIG(AHBRST, 20U)
#define GD32_RESET_GPIOE        GD32_RESET_CONFIG(AHBRST, 21U)
#define GD32_RESET_GPIOF        GD32_RESET_CONFIG(AHBRST, 22U)
#define GD32_RESET_GPIOG        GD32_RESET_CONFIG(AHBRST, 23U)
#define GD32_RESET_TMU          GD32_RESET_CONFIG(AHBRST, 26U)
#define GD32_RESET_SVPWM        GD32_RESET_CONFIG(AHBRST, 27U)
#define GD32_RESET_POC          GD32_RESET_CONFIG(AHBRST, 28U)
#define GD32_RESET_GTOC         GD32_RESET_CONFIG(AHBRST, 29U)

/* APB2 peripherals */
#define GD32_RESET_SYSCFG       GD32_RESET_CONFIG(APB2RST, 0U)
#define GD32_RESET_CMP          GD32_RESET_CONFIG(APB2RST, 1U)
#define GD32_RESET_ADC0         GD32_RESET_CONFIG(APB2RST, 8U)
#define GD32_RESET_ADC2         GD32_RESET_CONFIG(APB2RST, 9U)
#define GD32_RESET_TIMER0       GD32_RESET_CONFIG(APB2RST, 11U)
#define GD32_RESET_SPI0         GD32_RESET_CONFIG(APB2RST, 12U)
#define GD32_RESET_TIMER7       GD32_RESET_CONFIG(APB2RST, 13U)
#define GD32_RESET_TIMER1       GD32_RESET_CONFIG(APB2RST, 16U)
#define GD32_RESET_TIMER2       GD32_RESET_CONFIG(APB2RST, 17U)
#define GD32_RESET_GPTIMER0     GD32_RESET_CONFIG(APB2RST, 21U)
#define GD32_RESET_GPTIMER1     GD32_RESET_CONFIG(APB2RST, 22U)
#define GD32_RESET_CAN0         GD32_RESET_CONFIG(APB2RST, 30U)

/* APB1 peripherals */
#define GD32_RESET_CPTIMER0     GD32_RESET_CONFIG(APB1RST, 0U)
#define GD32_RESET_CPTIMER1     GD32_RESET_CONFIG(APB1RST, 1U)
#define GD32_RESET_CPTIMERW     GD32_RESET_CONFIG(APB1RST, 4U)
#define GD32_RESET_WWDGT        GD32_RESET_CONFIG(APB1RST, 12U)
#define GD32_RESET_UART0        GD32_RESET_CONFIG(APB1RST, 16U)
#define GD32_RESET_UART1        GD32_RESET_CONFIG(APB1RST, 17U)
#define GD32_RESET_UART2        GD32_RESET_CONFIG(APB1RST, 18U)
#define GD32_RESET_UART3        GD32_RESET_CONFIG(APB1RST, 19U)
#define GD32_RESET_I2C0         GD32_RESET_CONFIG(APB1RST, 21U)
#define GD32_RESET_PMU          GD32_RESET_CONFIG(APB1RST, 28U)
#define GD32_RESET_DAC          GD32_RESET_CONFIG(APB1RST, 29U)
#define GD32_RESET_CFMU         GD32_RESET_CONFIG(APB1RST, 30U)

/** @} */

/** @endcond */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RESET_GD32M531_H_ */
