/*
 * Copyright (c) 2026 GigaDevice Semiconductor Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_GD32M531_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_GD32M531_CLOCKS_H_

/**
 * @file
 * @brief GD32M53x (M531) peripheral clock control bindings.
 */

#include "gd32-clocks-common.h"

/** @cond INTERNAL_HIDDEN */

/**
 * @name Register offsets
 * @{
 */

#define GD32_AHBEN_OFFSET        0x14U
#define GD32_APB2EN_OFFSET       0x18U
#define GD32_APB1EN_OFFSET       0x1CU

/** @} */

/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */

/* AHB peripherals */
#define GD32_CLOCK_DMA0         GD32_CLOCK_CONFIG(AHBEN, 0U)
#define GD32_CLOCK_DMA1         GD32_CLOCK_CONFIG(AHBEN, 1U)
#define GD32_CLOCK_DMAMUX       GD32_CLOCK_CONFIG(AHBEN, 3U)
#define GD32_CLOCK_SRAM         GD32_CLOCK_CONFIG(AHBEN, 2U)
#define GD32_CLOCK_FMC          GD32_CLOCK_CONFIG(AHBEN, 4U)
#define GD32_CLOCK_CRC          GD32_CLOCK_CONFIG(AHBEN, 6U)
#define GD32_CLOCK_GPIOA        GD32_CLOCK_CONFIG(AHBEN, 16U)
#define GD32_CLOCK_GPIOB        GD32_CLOCK_CONFIG(AHBEN, 17U)
#define GD32_CLOCK_GPIOC        GD32_CLOCK_CONFIG(AHBEN, 18U)
#define GD32_CLOCK_GPIOD        GD32_CLOCK_CONFIG(AHBEN, 19U)
#define GD32_CLOCK_GPIOE        GD32_CLOCK_CONFIG(AHBEN, 20U)
#define GD32_CLOCK_GPIOF        GD32_CLOCK_CONFIG(AHBEN, 21U)
#define GD32_CLOCK_GPIOG        GD32_CLOCK_CONFIG(AHBEN, 22U)
#define GD32_CLOCK_TMU          GD32_CLOCK_CONFIG(AHBEN, 26U)
#define GD32_CLOCK_SVPWM        GD32_CLOCK_CONFIG(AHBEN, 27U)
#define GD32_CLOCK_POC          GD32_CLOCK_CONFIG(AHBEN, 28U)
#define GD32_CLOCK_GTOC         GD32_CLOCK_CONFIG(AHBEN, 29U)

/* APB2 peripherals */
#define GD32_CLOCK_SYSCFG       GD32_CLOCK_CONFIG(APB2EN, 0U)
#define GD32_CLOCK_CMP          GD32_CLOCK_CONFIG(APB2EN, 1U)
#define GD32_CLOCK_ADC0         GD32_CLOCK_CONFIG(APB2EN, 8U)
#define GD32_CLOCK_ADC2         GD32_CLOCK_CONFIG(APB2EN, 9U)
#define GD32_CLOCK_TIMER0       GD32_CLOCK_CONFIG(APB2EN, 11U)
#define GD32_CLOCK_SPI0         GD32_CLOCK_CONFIG(APB2EN, 12U)
#define GD32_CLOCK_TIMER7       GD32_CLOCK_CONFIG(APB2EN, 13U)
#define GD32_CLOCK_TIMER1       GD32_CLOCK_CONFIG(APB2EN, 16U)
#define GD32_CLOCK_TIMER2       GD32_CLOCK_CONFIG(APB2EN, 17U)
#define GD32_CLOCK_GPTIMER0     GD32_CLOCK_CONFIG(APB2EN, 21U)
#define GD32_CLOCK_GPTIMER1     GD32_CLOCK_CONFIG(APB2EN, 22U)
#define GD32_CLOCK_CAN0         GD32_CLOCK_CONFIG(APB2EN, 30U)

/* APB1 peripherals */
#define GD32_CLOCK_CPTIMER0     GD32_CLOCK_CONFIG(APB1EN, 0U)
#define GD32_CLOCK_CPTIMER1     GD32_CLOCK_CONFIG(APB1EN, 1U)
#define GD32_CLOCK_CPTIMERW     GD32_CLOCK_CONFIG(APB1EN, 4U)
#define GD32_CLOCK_WWDGT        GD32_CLOCK_CONFIG(APB1EN, 12U)
#define GD32_CLOCK_UART0        GD32_CLOCK_CONFIG(APB1EN, 16U)
#define GD32_CLOCK_UART1        GD32_CLOCK_CONFIG(APB1EN, 17U)
#define GD32_CLOCK_UART2        GD32_CLOCK_CONFIG(APB1EN, 18U)
#define GD32_CLOCK_UART3        GD32_CLOCK_CONFIG(APB1EN, 19U)
#define GD32_CLOCK_I2C0         GD32_CLOCK_CONFIG(APB1EN, 21U)
#define GD32_CLOCK_PMU          GD32_CLOCK_CONFIG(APB1EN, 28U)
#define GD32_CLOCK_DAC          GD32_CLOCK_CONFIG(APB1EN, 29U)
#define GD32_CLOCK_CFMU         GD32_CLOCK_CONFIG(APB1EN, 30U)

/** @} */

/** @endcond */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_GD32M531_CLOCKS_H_ */
